"""Best temporal post-processing pipeline for BirdCLEF 2026 soundscape inference.
Auto-generated by scripts/save_best_postproc.py — 2026-03-21 20:40

Method:  R14.08.MeanMax(w=0.5)→GM→cSEBBs
OOF AUC: 0.7927  (vs Gaussian 0.7749,  delta +0.0178)

Usage:
    from best_postproc import apply_best_postproc
    # probs: np.ndarray (N_WINDOWS, NUM_CLASSES) in [0, 1]
    smoothed = apply_best_postproc(probs)
"""
import numpy as np

N_WINDOWS = 12
NUM_CLASSES = 234

def apply_best_postproc(probs_file_T_C):
    """Best temporal post-processing: LSE(β=4.5) → GlobalMean(α=0.175) → cSEBBs(thr=0.06)."""
    import numpy as np
    X = probs_file_T_C.copy()
    T, C = X.shape
    eps = 1e-9
    logits = np.log(np.clip(X, eps, 1-eps) / np.clip(1-X, eps, 1-eps))
    beta, radius = 4.5, 1
    pad = np.pad(logits, ((radius, radius), (0, 0)), mode="edge")
    out_lse = np.zeros_like(logits)
    for t in range(T):
        window = pad[t:t+2*radius+1, :]
        out_lse[t] = (1.0/beta)*(beta*window).max(axis=0) + \
                     (1.0/beta)*np.log(np.exp(beta*(window-window.max(axis=0))).sum(axis=0))
    lse_probs = 1.0 / (1.0 + np.exp(-out_lse))
    gm = lse_probs.mean(axis=0)
    gm_probs = 0.825 * lse_probs + 0.175 * gm[None, :]
    out = gm_probs.copy()
    diff = np.abs(np.diff(gm_probs, axis=0))
    for t in range(T-1):
        for c in np.where(diff[t] > 0.06)[0]:
            seg = gm_probs[max(0,t-2):min(T,t+3), c]
            out[t, c] = 0.6 * gm_probs[t, c] + 0.4 * seg.mean()
    return np.clip(out, 0.0, 1.0)
