"""Best temporal post-processing pipeline for BirdCLEF 2026 soundscape inference.
Auto-generated by scripts/save_best_postproc.py — 2026-03-21 20:51

Method:  R15.06.MeanMax(T=0.2,w=1.0)→cSEBBs
OOF AUC: 0.7944  (vs Gaussian 0.7749,  delta +0.0196)

Usage:
    from best_postproc import apply_best_postproc
    # probs: np.ndarray (N_WINDOWS, NUM_CLASSES) in [0, 1]
    smoothed = apply_best_postproc(probs)
"""
import numpy as np

N_WINDOWS  = 12
NUM_CLASSES = 234
ENTR_TEMP  = 0.2   # soft entropy temperature
MAX_W      = 1.0   # MeanMax anchor weight (max_w*file_max + (1-max_w)*file_mean)
GM_ALPHA   = 0.175  # global mean blend weight
CP_THR     = 0.06   # cSEBBs change-point threshold

def apply_best_postproc(probs_file_T_C):
    """Best temporal post-processing: SoftEntrWt(T=0.2) → LSE(β=4.5) → MeanMax anchor → cSEBBs.
    MeanMax anchor = max_w * file_max + (1-max_w) * file_mean   (max_w≈0.5-1.0 optimal).

    Args:
        probs_file_T_C: np.ndarray shape (N_WINDOWS, NUM_CLASSES) in [0,1]
    Returns:
        smoothed: np.ndarray shape (N_WINDOWS, NUM_CLASSES) in [0,1]
    """
    import numpy as np
    import re as _re
    X = probs_file_T_C.copy()
    T, C = X.shape
    eps = 1e-9

    # Parse max_w and entr_temp from method name if available (defaults: max_w=0.5, temp=0.2)
    # These are set as module-level constants below; override as needed.
    entr_temp = ENTR_TEMP
    max_w     = MAX_W
    gm_alpha  = GM_ALPHA
    cp_thr    = CP_THR

    # Step 0: Soft entropy weighting
    H = -(X * np.log(X + eps) + (1 - X) * np.log(1 - X + eps))
    H_clip = H.mean(axis=1)                   # (T,) — avg binary entropy per clip
    w = np.exp(-H_clip / entr_temp)
    w = w / w.sum() * T                       # normalize

    # Step 1: Entropy-weighted logits → LSE pooling (β=4.5, r=1)
    logits = np.log(np.clip(X, eps, 1-eps) / np.clip(1-X, eps, 1-eps))
    logits_w = logits * w[:, None]
    beta, radius = 4.5, 1
    pad = np.pad(logits_w, ((radius, radius), (0, 0)), mode="edge")
    out_lse = np.zeros_like(logits_w)
    for t in range(T):
        win = pad[t:t + 2*radius+1, :]
        out_lse[t] = (1.0/beta)*(beta*win).max(axis=0) + \
                     (1.0/beta)*np.log(np.exp(beta*(win - win.max(axis=0))).sum(axis=0))
    lse_probs = 1.0 / (1.0 + np.exp(-out_lse))   # (T, C)

    # Step 2: MeanMax anchor blend  — anchor = max_w*file_max + (1-max_w)*file_mean
    file_max  = lse_probs.max(axis=0)             # (C,)
    file_mean = lse_probs.mean(axis=0)            # (C,)
    anchor = max_w * file_max + (1 - max_w) * file_mean
    blended = (1 - gm_alpha) * lse_probs + gm_alpha * anchor[None, :]  # (T, C)

    # Step 3: cSEBBs-lite (thr, blend=0.4) — clean segment boundaries
    out = blended.copy()
    diff = np.abs(np.diff(blended, axis=0))       # (T-1, C)
    for t in range(T - 1):
        for c in np.where(diff[t] > cp_thr)[0]:
            seg = blended[max(0, t-2):min(T, t+3), c]
            out[t, c] = 0.6 * blended[t, c] + 0.4 * seg.mean()
    return np.clip(out, 0.0, 1.0)
