"""Best temporal post-processing pipeline for BirdCLEF 2026 soundscape inference.
Auto-generated by scripts/save_best_postproc.py — 2026-03-21 21:45

Method:  R22.01.DualAnchor(nw=0.40,a=0.38)→cSEBBs
OOF AUC: 0.8038  (vs Gaussian 0.7749,  delta +0.0289)

Usage:
    from best_postproc import apply_best_postproc
    # probs: np.ndarray (N_WINDOWS, NUM_CLASSES) in [0, 1]
    smoothed = apply_best_postproc(probs)
"""
import numpy as np

N_WINDOWS  = 12
NUM_CLASSES = 234
ENTR_TEMP  = 0.1   # soft entropy temperature
MAX_W      = 1.0   # MeanMax anchor weight (max_w*file_max + (1-max_w)*file_mean)
GM_ALPHA   = 0.38  # global anchor blend weight (alpha)
CP_THR     = 0.06   # cSEBBs change-point threshold
NOR_W      = 0.4   # DualAnchor: weight of NoisyOR (1-NOR_W = weight of GlobalMax)

def apply_best_postproc(probs_file_T_C):
    """Best post-processing: SoftEntrWt → LSE → DualAnchor(NOR+Max) → cSEBBs.
    DualAnchor = NOR_W * NoisyOR + (1-NOR_W) * file_max   (combines MIL + extreme pooling).
    """
    import numpy as np
    X = probs_file_T_C.copy()
    T, C = X.shape
    eps = 1e-9
    entr_temp = ENTR_TEMP
    alpha     = GM_ALPHA
    nor_w     = NOR_W
    cp_thr    = CP_THR

    # Step 0: Soft entropy weighting
    H = -(X * np.log(X + eps) + (1 - X) * np.log(1 - X + eps))
    H_clip = H.mean(axis=1)
    w = np.exp(-H_clip / entr_temp)
    w = w / w.sum() * T

    # Step 1: LSE pooling (β=4.5, r=1)
    logits = np.log(np.clip(X, eps, 1-eps) / np.clip(1-X, eps, 1-eps))
    logits_w = logits * w[:, None]
    beta, radius = 4.5, 1
    pad = np.pad(logits_w, ((radius, radius), (0, 0)), mode="edge")
    out_lse = np.zeros_like(logits_w)
    for t in range(T):
        win = pad[t:t + 2*radius+1, :]
        out_lse[t] = (1.0/beta)*(beta*win).max(axis=0) + \
                     (1.0/beta)*np.log(np.exp(beta*(win - win.max(axis=0))).sum(axis=0))
    lse_probs = 1.0 / (1.0 + np.exp(-out_lse))

    # Step 2: Dual anchor = nor_w * NoisyOR + (1-nor_w) * file_max
    nor_anchor = 1.0 - np.prod(1.0 - lse_probs, axis=0)   # (C,)
    max_anchor = lse_probs.max(axis=0)                      # (C,)
    anchor = nor_w * nor_anchor + (1 - nor_w) * max_anchor
    blended = (1 - alpha) * lse_probs + alpha * anchor[None, :]

    # Step 3: cSEBBs-lite
    out = blended.copy()
    diff = np.abs(np.diff(blended, axis=0))
    for t in range(T - 1):
        for c in np.where(diff[t] > cp_thr)[0]:
            seg = blended[max(0, t-2):min(T, t+3), c]
            out[t, c] = 0.6 * blended[t, c] + 0.4 * seg.mean()
    return np.clip(out, 0.0, 1.0)
